SELECT ROUND(AVG(IFNULL(LENGTH, 10)), 2) AS AVERAGE_LENGTH
FROM FISH_INFO

-- SELECT ROUND(AVG(L.LENGTH), 2) AS AVERAGE_LENGTH
-- FROM
--     (SELECT IF(LENGTH IS NULL, 10, LENGTH) AS LENGTH
--      FROM FISH_INFO) L